apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jangos-sdad-app
  labels:
    app: test-jangos-sdad-app
    applicationId: app_7063cddb-a868-4897-8951-cb8ddc3b1157
    version: v0.0.1
spec:
  selector:
    matchLabels:
      app: test-jangos-sdad-app
  template:
    metadata:
      labels:
        app: test-jangos-sdad-app
