apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 123
          targetPort: 1233
          protocol: UDP
        - port: 345
          targetPort: 534
          protocol: UDP
      healthChecks: []
      name: tronsadd-app-main
      imagePullPolicy: Always
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: tronsadd-app
    version: v0.0.1
    applicationId: app_e62ea0eb-9b96-4d94-88e0-7546524394d0
    projectId: project_e1f18706-a3dc-4898-9a85-16e7399dd8b9
    organizationId: org_a09b6925-5b61-46d2-8d78-e1a1079bde03
    environmentId: env_86edc3b5-c261-4e41-a6da-934dd7327718
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Job
  name: tronsadd-app
  cronTab: ''
  serviceType: ClusterIP
  namespace: fdghhhhtryhbgfv-prod
