apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: fdgdfgfhfghdfbcgvbdfscvvcvxvcxv43w534
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fdgdfgfhfghdfbcgvbdfscvvcvxvcxv43w534
