apiVersion: v1
kind: Namespace
metadata:
  name: riot
  labels:
    environment-id: env_a8aaa916-397c-4979-b6bc-03345c2ed71c
    project-id: project_47e36bd8-be79-41a7-bc0a-8034da4b53a3
    project-name: ohios
    environment-name: chirath
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
