apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: jackson-thirtenn-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jackson-thirtenn-app
