apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: new-world-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: new-world-app
