apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: ' new application test 434    '
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ' new application test 434    '
