apiVersion: v1
kind: Namespace
metadata:
  name: fdghhhhtryhbgfv-dev
  labels:
    environment-id: env_44339a25-1514-46f7-9965-f525bf27f982
    project-id: project_e1f18706-a3dc-4898-9a85-16e7399dd8b9
    project-name: new-testing-project-asdewqe
    environment-name: dev
    organization-id: org_a09b6925-5b61-46d2-8d78-e1a1079bde03
