apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: dfgdfgghjj6rty
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dfgdfgghjj6rty
