apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: 12sad3abcx4w3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 12sad3abcx4w3
