apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: 'new application test '
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 'new application test '
