apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: dggdf
    applicationId: app_1133cb02-8a76-40ee-bd31-f8ea52accd7f
    version: v0.0.1
  name: dggdf
spec:
  selector:
    app: dggdf
