apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: sdfjgsdfsdf
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sdfjgsdfsdf
