apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: drfgssdfg-main
      imagePullPolicy: Always
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: drfgssdfg
    version: v0.0.1
    applicationId: app_0425bce9-487d-41bc-8355-5f4050409c69
    projectId: project_e1f18706-a3dc-4898-9a85-16e7399dd8b9
    organizationId: org_a09b6925-5b61-46d2-8d78-e1a1079bde03
    environmentId: env_2431c235-d047-4516-a8d9-a789880482d7
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: drfgssdfg
  cronTab: ''
  serviceType: ClusterIP
  namespace: fdghhhhtryhbgfv-staging
