apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-pdsaovcnvxcv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-pdsaovcnvxcv
